const STATUS_TEXT={normal:'عادي',new:'جديد',sale:'خصم',sold:'نفد',featured:'مميز',coming:'قريباً'};
const seedP=[
{id:'rfid-attendance',type:'product',title:'نظام RFID للحضور',category:'Arduino',price_iqd:12000,price_usd:9,old_iqd:15000,old_usd:11.5,status:'new',statusText:'جديد',short:'كود كامل + مخطط توصيل + قائمة مكتبات + ملف شرح.',description:'مشروع متكامل لبناء نظام حضور باستخدام Arduino وقارئ RFID.',features:['كود Arduino كامل','مخطط التوصيل','قائمة المكتبات','ملف شرح PDF'],youtube:'https://www.youtube.com/',images:[],active:true},
{id:'ble-mouse',type:'product',title:'مشروع BLE Mouse',category:'ESP32',price_iqd:15000,price_usd:11.5,old_iqd:20000,old_usd:15,status:'sale',statusText:'خصم',short:'ESP32 + Joystick للتحكم بالمؤشر لاسلكياً.',description:'مشروع تحكم بالمؤشر عبر Bluetooth باستخدام ESP32 وJoystick.',features:['كود ESP32','شرح التوصيل','إعداد BLE'],youtube:'https://www.youtube.com/',images:[],active:true},
{id:'sensor-guide',type:'product',title:'دليل الحساسات العملي',category:'Guides',price_iqd:10000,price_usd:7.5,old_iqd:null,old_usd:null,status:'normal',statusText:'عادي',short:'مرجع عربي سريع للحساسات الأكثر استخداماً.',description:'دليل مرتب للحساسات الشائعة مع فكرة العمل والتوصيل.',features:['شرح مبسط','أمثلة توصيل','أكواد تجريبية'],youtube:'',images:[],active:true},
{id:'smart-parking',type:'product',title:'نظام الموقف الذكي',category:'Arduino',price_iqd:9000,price_usd:7,old_iqd:null,old_usd:null,status:'sold',statusText:'نفد',short:'Servo + LCD + حساسات لموقف سيارات ذكي.',description:'مشروع كامل لموقف ذكي مع عداد أماكن متبقية وبوابة Servo وشاشة LCD.',features:['كود المشروع','مخطط التوصيل','منطق الدخول والخروج'],youtube:'',images:[],active:true},
{id:'esp32-web-dashboard',type:'product',title:'لوحة تحكم ESP32 Web',category:'ESP32',price_iqd:14000,price_usd:10.5,old_iqd:null,old_usd:null,status:'featured',statusText:'مميز',short:'واجهة ويب للتحكم بالمخارج والحساسات.',description:'مشروع ESP32 بواجهة ويب متجاوبة للتحكم بالمخارج وقراءة الحساسات.',features:['واجهة متجاوبة','ESP32 AP / Wi-Fi','تحكم لحظي'],youtube:'',images:[],active:true}
];
const seedC=[
{id:'arduino-basics',type:'course',title:'أساسيات Arduino من الصفر',category:'Arduino',price_iqd:30000,price_usd:23,old_iqd:40000,old_usd:30,status:'sale',statusText:'خصم',short:'ابدأ من الأساسيات ووصل للمشاريع العملية.',description:'دورة تطبيقية مرتبة للمبتدئ.',features:['شرح عربي','تمارين عملية','ملفات كود'],youtube:'https://www.youtube.com/',images:[],active:true},
{id:'protocols-course',type:'course',title:'UART • I²C • SPI ببساطة',category:'Electronics',price_iqd:22000,price_usd:17,old_iqd:null,old_usd:null,status:'new',statusText:'جديد',short:'فهم بروتوكولات الاتصال من خلال أمثلة عملية.',description:'دورة مختصرة توضح الفرق بين UART وI²C وSPI.',features:['شرح البتات','أمثلة عملية','مقارنة البروتوكولات'],youtube:'https://www.youtube.com/',images:[],active:true},
{id:'esp32-wireless',type:'course',title:'ESP32: Wi-Fi و Bluetooth',category:'ESP32',price_iqd:35000,price_usd:27,old_iqd:null,old_usd:null,status:'coming',statusText:'قريباً',short:'مشاريع لاسلكية ولوحات ويب باستخدام ESP32.',description:'دورة عملية للبدء مع Wi-Fi وBluetooth على ESP32.',features:['Wi-Fi','BLE','Web Control'],youtube:'',images:[],active:true}
];
function migrateStored(list,seeds){const legacy={rfid:'rfid-attendance',ble:'ble-mouse'};const normalized=(list||[]).map(x=>({...x,id:legacy[x.id]||x.id}));const byId=new Map(normalized.map(x=>[x.id,x]));for(const seed of seeds){if(!byId.has(seed.id))byId.set(seed.id,seed)}return [...byId.values()]}
let products=migrateStored(JSON.parse(localStorage.getItem('wt_products')||'null'),seedP),courses=migrateStored(JSON.parse(localStorage.getItem('wt_courses')||'null'),seedC);
let consultations=JSON.parse(localStorage.getItem('wt_consults')||'null')||{c1:{price:20000,desc:'مكالمة فيديو لمدة ساعة.'},c2:{price:100000,desc:'متابعة شهرية + 4 مكالمات.'}};
let settings=JSON.parse(localStorage.getItem('wt_settings')||'null')||{storeName:'ورشة تك | warshaTik',telegram:'https://t.me/HW2DMbot',whatsapp:'+964 786 741 9185',currency:'IQD'};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let editing=null,currentImages=[],dragIndex=null;
function save(){localStorage.setItem('wt_products',JSON.stringify(products));localStorage.setItem('wt_courses',JSON.stringify(courses))}
save();
function badge(s){return'badge '+(s||'normal')}function label(x){return x.statusText||STATUS_TEXT[x.status]||'عادي'}
function rows(list){return list.map(x=>`<tr><td><strong>${x.title}</strong><br><small>${x.category}</small></td><td>${Number(x.price_iqd).toLocaleString()}</td><td>$${x.price_usd}</td><td><span class="${badge(x.status)}">${label(x)}</span></td><td><button class="mini" onclick="editItem('${x.type}','${x.id}')">تعديل</button> <button class="mini" onclick="delItem('${x.type}','${x.id}')">حذف</button></td></tr>`).join('')}
function render(){const q=$('#search').value.toLowerCase();$('#productRows').innerHTML=rows(products.filter(x=>x.title.toLowerCase().includes(q)));$('#courseRows').innerHTML=rows(courses);$('#statProducts').textContent=products.length;$('#statCourses').textContent=courses.length;$('#statSold').textContent=[...products,...courses].filter(x=>x.status==='sold').length;$('#statActive').textContent=[...products,...courses].filter(x=>x.active).length;$('#recent').innerHTML=[...products,...courses].slice(0,5).map(x=>`<div class="recent"><strong>${x.title}</strong> — <span class="${badge(x.status)}">${label(x)}</span></div>`).join('')}
function renderImages(){const wrap=$('#imageList');wrap.innerHTML=currentImages.map((src,i)=>`<div class="image-item" draggable="true" data-i="${i}"><img src="${src}"><small>${i===0?'★ الصورة الرئيسية':'اسحب للترتيب'}</small><button type="button" data-remove="${i}">حذف</button></div>`).join('');wrap.querySelectorAll('.image-item').forEach(el=>{el.addEventListener('dragstart',()=>{dragIndex=Number(el.dataset.i);el.classList.add('dragging')});el.addEventListener('dragend',()=>el.classList.remove('dragging'));el.addEventListener('dragover',e=>e.preventDefault());el.addEventListener('drop',e=>{e.preventDefault();const to=Number(el.dataset.i);if(dragIndex===null||dragIndex===to)return;const[m]=currentImages.splice(dragIndex,1);currentImages.splice(to,0,m);dragIndex=null;renderImages()})});wrap.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{currentImages.splice(Number(b.dataset.remove),1);renderImages()})}
function setStatusText(status,force=true){const input=$('#statusText');if(force||!input.value)input.value=STATUS_TEXT[status]||'عادي';input.readOnly=true;$('#editStatusText').textContent='✎'}
function openEditor(type,item=null){editing=item?.id||null;currentImages=[...(item?.images||[])];$('#modalTitle').textContent=item?'تعديل':'إضافة';$('#editType').value=type;$('#title').value=item?.title||'';$('#category').value=item?.category||'';$('#price_iqd').value=item?.price_iqd||'';$('#price_usd').value=item?.price_usd||'';$('#old_iqd').value=item?.old_iqd??'';$('#old_usd').value=item?.old_usd??'';$('#status').value=item?.status||'normal';$('#statusText').value=item?.statusText||STATUS_TEXT[$('#status').value];$('#statusText').readOnly=true;$('#editStatusText').textContent='✎';$('#short').value=item?.short||'';$('#description').value=item?.description||'';$('#features').value=(item?.features||[]).join('\n');$('#youtube').value=item?.youtube||'';$('#active').checked=item?.active??true;renderImages();$('#modal').classList.add('open')}
function editItem(type,id){const a=type==='course'?courses:products;openEditor(type,a.find(x=>x.id===id))}function delItem(type,id){if(!confirm('حذف؟'))return;if(type==='course')courses=courses.filter(x=>x.id!==id);else products=products.filter(x=>x.id!==id);save();render()}function close(){ $('#modal').classList.remove('open') }
$('#status').addEventListener('change',e=>setStatusText(e.target.value,true));
$('#editStatusText').addEventListener('click',()=>{const input=$('#statusText');input.readOnly=!input.readOnly;$('#editStatusText').textContent=input.readOnly?'✎':'✓';if(!input.readOnly){input.focus();input.select()}});
$('#imageInput').addEventListener('change',async e=>{for(const file of e.target.files){if(!file.type.startsWith('image/'))continue;const src=await new Promise(res=>{const r=new FileReader();r.onload=()=>res(r.result);r.readAsDataURL(file)});currentImages.push(src)}e.target.value='';renderImages()});
$('#form').onsubmit=e=>{e.preventDefault();const type=$('#editType').value;const x={id:editing||type+'-'+Date.now(),type,title:$('#title').value,category:$('#category').value,price_iqd:Number($('#price_iqd').value),price_usd:Number($('#price_usd').value),old_iqd:$('#old_iqd').value?Number($('#old_iqd').value):null,old_usd:$('#old_usd').value?Number($('#old_usd').value):null,status:$('#status').value,statusText:$('#statusText').value||STATUS_TEXT[$('#status').value],short:$('#short').value,description:$('#description').value,features:$('#features').value.split('\n').filter(Boolean),youtube:$('#youtube').value,images:currentImages,active:$('#active').checked};if(type==='course')courses=editing?courses.map(y=>y.id===editing?x:y):[...courses,x];else products=editing?products.map(y=>y.id===editing?x:y):[...products,x];try{save()}catch(err){alert('الصور كبيرة على التخزين المحلي. هذا مؤقت؛ عند ربط R2 سترفع الصور مباشرة بدون هذا الحد.')}render();close()};
$$('.nav').forEach(b=>b.onclick=()=>{$$('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(v=>v.classList.remove('active'));$('#'+b.dataset.view).classList.add('active');$('#pageTitle').textContent=b.textContent.trim()});$('#quickAdd').onclick=()=>openEditor('product');$('#addProduct').onclick=()=>openEditor('product');$('#addCourse').onclick=()=>openEditor('course');$('#close').onclick=close;$('#cancel').onclick=close;$('#search').oninput=render;
$('#c1price').value=consultations.c1.price;$('#c1desc').value=consultations.c1.desc;$('#c2price').value=consultations.c2.price;$('#c2desc').value=consultations.c2.desc;$('#saveC1').onclick=()=>{consultations.c1={price:Number($('#c1price').value),desc:$('#c1desc').value};localStorage.setItem('wt_consults',JSON.stringify(consultations))};$('#saveC2').onclick=()=>{consultations.c2={price:Number($('#c2price').value),desc:$('#c2desc').value};localStorage.setItem('wt_consults',JSON.stringify(consultations))};$('#storeName').value=settings.storeName;$('#telegram').value=settings.telegram;$('#whatsapp').value=settings.whatsapp;$('#currency').value=settings.currency;$('#saveSettings').onclick=()=>{settings={storeName:$('#storeName').value,telegram:$('#telegram').value,whatsapp:$('#whatsapp').value,currency:$('#currency').value};localStorage.setItem('wt_settings',JSON.stringify(settings))};render();