window.WARSHA_DATA={products:[
{id:'rfid-attendance',type:'product',category:'Arduino',title:'نظام RFID للحضور',short:'كود كامل + مخطط توصيل + قائمة مكتبات + ملف شرح.',description:'مشروع متكامل لبناء نظام حضور باستخدام Arduino وقارئ RFID. يتضمن الكود، التوصيلات، المكتبات المطلوبة، ملاحظات التشغيل وخطوات التعديل.',price_iqd:12000,price_usd:9,old_price_iqd:15000,old_price_usd:11.5,status:'new',statusText:'جديد',features:['كود Arduino كامل','مخطط التوصيل','قائمة المكتبات','ملف شرح PDF','ملاحظات للتعديل والتخصيص'],images:['RFID Project','Circuit Diagram','Code Preview'],youtube:'https://www.youtube.com/',active:true},
{id:'ble-mouse',type:'product',category:'ESP32',title:'مشروع BLE Mouse',short:'ESP32 + Joystick للتحكم بالمؤشر لاسلكياً.',description:'مشروع تحكم بالمؤشر عبر Bluetooth باستخدام ESP32 وJoystick، مع بنية كود قابلة للتعديل وإضافة الأزرار والوظائف.',price_iqd:15000,price_usd:11.5,old_price_iqd:20000,old_price_usd:15,status:'sale',statusText:'خصم',features:['كود ESP32','شرح التوصيل','إعداد BLE','تعديل الحساسية والسرعة','ملف تعليمات'],images:['BLE Mouse','ESP32 Wiring','Joystick Setup'],youtube:'https://www.youtube.com/',active:true},
{id:'sensor-guide',type:'product',category:'Guides',title:'دليل الحساسات العملي',short:'مرجع عربي سريع للحساسات الأكثر استخداماً.',description:'دليل مرتب للحساسات الشائعة مع فكرة العمل، التوصيل، الملاحظات المهمة، وأمثلة كود قصيرة.',price_iqd:10000,price_usd:7.5,old_price_iqd:null,old_price_usd:null,status:'normal',statusText:'',features:['شرح مبسط','أمثلة توصيل','أكواد تجريبية','ملاحظات اختيار الحساس'],images:['Sensors Guide','Examples','Reference Pages'],youtube:'',active:true},
{id:'smart-parking',type:'product',category:'Arduino',title:'نظام الموقف الذكي',short:'Servo + LCD + حساسات لموقف سيارات ذكي.',description:'مشروع كامل لموقف ذكي مع عداد أماكن متبقية وبوابة Servo وشاشة LCD.',price_iqd:9000,price_usd:7,old_price_iqd:null,old_price_usd:null,status:'sold',statusText:'نفد',features:['كود المشروع','مخطط التوصيل','منطق الدخول والخروج','إعداد الشاشة'],images:['Parking System','Gate','LCD'],youtube:'',active:true},
{id:'esp32-web-dashboard',type:'product',category:'ESP32',title:'لوحة تحكم ESP32 Web',short:'واجهة ويب للتحكم بالمخارج والحساسات.',description:'مشروع ESP32 بواجهة ويب متجاوبة للتحكم بالمخارج وقراءة الحساسات من الهاتف أو الحاسوب.',price_iqd:14000,price_usd:10.5,old_price_iqd:null,old_price_usd:null,status:'featured',statusText:'مميز',features:['واجهة متجاوبة','ESP32 AP / Wi-Fi','تحكم لحظي','كود منظم'],images:['Web Dashboard','Mobile View','ESP32'],youtube:'',active:true}],
courses:[
{id:'arduino-basics',type:'course',category:'Arduino',title:'أساسيات Arduino من الصفر',short:'ابدأ من الأساسيات ووصل للمشاريع العملية.',description:'دورة تطبيقية مرتبة للمبتدئ تغطي البرمجة الأساسية، المداخل والمخارج، الحساسات، PWM وبناء مشاريع حقيقية.',price_iqd:30000,price_usd:23,old_price_iqd:40000,old_price_usd:30,status:'sale',statusText:'خصم 25%',features:['شرح عربي','تمارين عملية','ملفات كود','مشاريع تطبيقية'],images:['Arduino Course','Lesson Preview','Projects'],youtube:'https://www.youtube.com/',active:true},
{id:'protocols-course',type:'course',category:'Electronics',title:'UART • I²C • SPI ببساطة',short:'فهم بروتوكولات الاتصال من خلال أمثلة عملية.',description:'دورة مختصرة توضح الفرق بين UART وI²C وSPI، طريقة انتقال البيانات، واستخدامها مع Arduino وESP32.',price_iqd:22000,price_usd:17,old_price_iqd:null,old_price_usd:null,status:'new',statusText:'جديد',features:['شرح البتات','أمثلة عملية','مقارنة البروتوكولات','ملفات كود'],images:['Protocols','I2C','SPI/UART'],youtube:'https://www.youtube.com/',active:true},
{id:'esp32-wireless',type:'course',category:'ESP32',title:'ESP32: Wi-Fi و Bluetooth',short:'مشاريع لاسلكية ولوحات ويب باستخدام ESP32.',description:'دورة عملية للبدء مع Wi-Fi وBluetooth على ESP32 وبناء واجهات تحكم ومشاريع متصلة.',price_iqd:35000,price_usd:27,old_price_iqd:null,old_price_usd:null,status:'coming',statusText:'قريباً',features:['Wi-Fi','BLE','Web Control','مشاريع عملية'],images:['ESP32 Course','WiFi','Bluetooth'],youtube:'',active:true}]};