const seedP=[{id:'rfid',type:'product',title:'نظام RFID للحضور',category:'Arduino',price_iqd:12000,price_usd:9,old_iqd:15000,old_usd:11.5,status:'new',statusText:'جديد',short:'كود كامل + مخطط توصيل + قائمة مكتبات.',description:'مشروع RFID كامل.',features:['الكود','المخطط','المكتبات'],youtube:'',images:[],active:true},{id:'ble',type:'product',title:'مشروع BLE Mouse',category:'ESP32',price_iqd:15000,price_usd:11.5,old_iqd:20000,old_usd:15,status:'sale',statusText:'خصم',short:'ESP32 + Joystick.',description:'BLE Mouse project',features:['الكود','التوصيل'],youtube:'',images:[],active:true}];
const seedC=[{id:'arduino-basics',type:'course',title:'أساسيات Arduino',category:'Arduino',price_iqd:30000,price_usd:23,old_iqd:40000,old_usd:30,status:'sale',statusText:'خصم 25%',short:'دورة للمبتدئ.',description:'دورة Arduino عملية.',features:['شرح','تمارين'],youtube:'',images:[],active:true}];
let products=JSON.parse(localStorage.getItem('wt_products')||'null')||seedP,courses=JSON.parse(localStorage.getItem('wt_courses')||'null')||seedC;
let consultations=JSON.parse(localStorage.getItem('wt_consults')||'null')||{c1:{price:20000,desc:'مكالمة فيديو لمدة ساعة.'},c2:{price:100000,desc:'متابعة شهرية + 4 مكالمات.'}};
let settings=JSON.parse(localStorage.getItem('wt_settings')||'null')||{storeName:'ورشة تك | warshaTik',telegram:'https://t.me/HW2DMbot',whatsapp:'+964 786 741 9185',currency:'IQD'};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let editing=null,currentImages=[],dragIndex=null;
function save(){localStorage.setItem('wt_products',JSON.stringify(products));localStorage.setItem('wt_courses',JSON.stringify(courses))}
function badge(s){return'badge '+(s||'normal')}function label(x){return x.statusText||({normal:'عادي',new:'جديد',sale:'خصم',sold:'نفد',featured:'مميز',coming:'قريباً'}[x.status]||'عادي')}
function rows(list){return list.map(x=>`<tr><td><strong>${x.title}</strong><br><small>${x.category}</small></td><td>${Number(x.price_iqd).toLocaleString()}</td><td>$${x.price_usd}</td><td><span class="${badge(x.status)}">${label(x)}</span></td><td><button class="mini" onclick="editItem('${x.type}','${x.id}')">تعديل</button> <button class="mini" onclick="delItem('${x.type}','${x.id}')">حذف</button></td></tr>`).join('')}
function render(){const q=$('#search').value.toLowerCase();$('#productRows').innerHTML=rows(products.filter(x=>x.title.toLowerCase().includes(q)));$('#courseRows').innerHTML=rows(courses);$('#statProducts').textContent=products.length;$('#statCourses').textContent=courses.length;$('#statSold').textContent=[...products,...courses].filter(x=>x.status==='sold').length;$('#statActive').textContent=[...products,...courses].filter(x=>x.active).length;$('#recent').innerHTML=[...products,...courses].slice(0,5).map(x=>`<div class="recent"><strong>${x.title}</strong> — <span class="${badge(x.status)}">${label(x)}</span></div>`).join('')}
function renderImages(){const wrap=$('#imageList');wrap.innerHTML=currentImages.map((src,i)=>`<div class="image-item" draggable="true" data-i="${i}"><img src="${src}"><small>${i===0?'★ الصورة الرئيسية':'اسحب للترتيب'}</small><button type="button" data-remove="${i}">حذف</button></div>`).join('');wrap.querySelectorAll('.image-item').forEach(el=>{el.addEventListener('dragstart',()=>{dragIndex=Number(el.dataset.i);el.classList.add('dragging')});el.addEventListener('dragend',()=>el.classList.remove('dragging'));el.addEventListener('dragover',e=>e.preventDefault());el.addEventListener('drop',e=>{e.preventDefault();const to=Number(el.dataset.i);if(dragIndex===null||dragIndex===to)return;const [m]=currentImages.splice(dragIndex,1);currentImages.splice(to,0,m);dragIndex=null;renderImages()})});wrap.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{currentImages.splice(Number(b.dataset.remove),1);renderImages()})}
function openEditor(type,item=null){editing=item?.id||null;currentImages=[...(item?.images||[])];$('#modalTitle').textContent=item?'تعديل':'إضافة';$('#editType').value=type;$('#title').value=item?.title||'';$('#category').value=item?.category||'';$('#price_iqd').value=item?.price_iqd||'';$('#price_usd').value=item?.price_usd||'';$('#old_iqd').value=item?.old_iqd||'';$('#old_usd').value=item?.old_usd||'';$('#status').value=item?.status||'normal';$('#statusText').value=item?.statusText||'';$('#short').value=item?.short||'';$('#description').value=item?.description||'';$('#features').value=(item?.features||[]).join('\n');$('#youtube').value=item?.youtube||'';$('#active').checked=item?.active??true;renderImages();$('#modal').classList.add('open')}
function editItem(type,id){const a=type==='course'?courses:products;openEditor(type,a.find(x=>x.id===id))}function delItem(type,id){if(!confirm('حذف؟'))return;if(type==='course')courses=courses.filter(x=>x.id!==id);else products=products.filter(x=>x.id!==id);save();render()}function close(){ $('#modal').classList.remove('open') }
$('#imageInput').addEventListener('change',async e=>{for(const file of e.target.files){if(!file.type.startsWith('image/'))continue;const src=await new Promise(res=>{const r=new FileReader();r.onload=()=>res(r.result);r.readAsDataURL(file)});currentImages.push(src)}e.target.value='';renderImages()});
$('#form').onsubmit=e=>{e.preventDefault();const type=$('#editType').value;const x={id:editing||type+'-'+Date.now(),type,title:$('#title').value,category:$('#category').value,price_iqd:Number($('#price_iqd').value),price_usd:Number($('#price_usd').value),old_iqd:$('#old_iqd').value?Number($('#old_iqd').value):null,old_usd:$('#old_usd').value?Number($('#old_usd').value):null,status:$('#status').value,statusText:$('#statusText').value,short:$('#short').value,description:$('#description').value,features:$('#features').value.split('\n').filter(Boolean),youtube:$('#youtube').value,images:currentImages,active:$('#active').checked};if(type==='course')courses=editing?courses.map(y=>y.id===editing?x:y):[...courses,x];else products=editing?products.map(y=>y.id===editing?x:y):[...products,x];try{save()}catch(err){alert('الصور كبيرة على التخزين المحلي. هذا مؤقت؛ عند ربط R2 سترفع الصور مباشرة بدون هذا الحد.')}render();close()};
$$('.nav').forEach(b=>b.onclick=()=>{$$('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(v=>v.classList.remove('active'));$('#'+b.dataset.view).classList.add('active');$('#pageTitle').textContent=b.textContent.trim()});$('#quickAdd').onclick=()=>openEditor('product');$('#addProduct').onclick=()=>openEditor('product');$('#addCourse').onclick=()=>openEditor('course');$('#close').onclick=close;$('#cancel').onclick=close;$('#search').oninput=render;
$('#c1price').value=consultations.c1.price;$('#c1desc').value=consultations.c1.desc;$('#c2price').value=consultations.c2.price;$('#c2desc').value=consultations.c2.desc;$('#saveC1').onclick=()=>{consultations.c1={price:Number($('#c1price').value),desc:$('#c1desc').value};localStorage.setItem('wt_consults',JSON.stringify(consultations))};$('#saveC2').onclick=()=>{consultations.c2={price:Number($('#c2price').value),desc:$('#c2desc').value};localStorage.setItem('wt_consults',JSON.stringify(consultations))};$('#storeName').value=settings.storeName;$('#telegram').value=settings.telegram;$('#whatsapp').value=settings.whatsapp;$('#currency').value=settings.currency;$('#saveSettings').onclick=()=>{settings={storeName:$('#storeName').value,telegram:$('#telegram').value,whatsapp:$('#whatsapp').value,currency:$('#currency').value};localStorage.setItem('wt_settings',JSON.stringify(settings))};render();